#############################################################################
# Makefile for building: Factory_test
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  Factory_test.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile Factory_test.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/local/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Factory_test1.0.0
DISTDIR = /root/work/Factory_test/.tmp/Factory_test1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -L/usr/local/include -lavcodec -lavdevice -lavfilter -lavformat -lavutil -lswresample -lswscale -lftp -ludev -lasound -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		core/func/BrightTest.cpp \
		core/func/CamaraTest.cpp \
		core/func/EdidTest.cpp \
		core/func/FanTest.cpp \
		core/func/FuncBase.cpp \
		core/func/FuncTest.cpp \
		core/func/HddTest.cpp \
		core/func/MemTest.cpp \
		core/func/NetTest.cpp \
		core/func/NextProcess.cpp \
		core/func/SoundTest.cpp \
		core/func/StressTest.cpp \
		core/func/UploadMes.cpp \
		core/func/UsbTest.cpp \
		core/func/WifiTest.cpp \
		core/ui/UiHandle.cpp \
		utils/fac_log.cpp \
		utils/fac_utils.cpp \
		core/ui/DisplayTestWindow.cpp \
		core/ui/MainTestWindow.cpp \
		core/ui/StressTestWindow.cpp \
		core/ui/messageform.cpp \
		core/control/Control.cpp \
		core/ui/VideoTestThread.cpp \
		core/ui/ImageTestThread.cpp moc_Control.cpp \
		moc_ui.cpp \
		moc_UiHandle.cpp \
		moc_messageform.cpp \
		moc_VideoTestThread.cpp \
		moc_ImageTestThread.cpp
OBJECTS       = main.o \
		BrightTest.o \
		CamaraTest.o \
		EdidTest.o \
		FanTest.o \
		FuncBase.o \
		FuncTest.o \
		HddTest.o \
		MemTest.o \
		NetTest.o \
		NextProcess.o \
		SoundTest.o \
		StressTest.o \
		UploadMes.o \
		UsbTest.o \
		WifiTest.o \
		UiHandle.o \
		fac_log.o \
		fac_utils.o \
		DisplayTestWindow.o \
		MainTestWindow.o \
		StressTestWindow.o \
		messageform.o \
		Control.o \
		VideoTestThread.o \
		ImageTestThread.o \
		moc_Control.o \
		moc_ui.o \
		moc_UiHandle.o \
		moc_messageform.o \
		moc_VideoTestThread.o \
		moc_ImageTestThread.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Factory_test.pro inc/Control.h \
		inc/EdidTest.h \
		inc/fac_log.h \
		inc/fac_utils.h \
		inc/FuncBase.h \
		inc/FuncTest.h \
		inc/NetTest.h \
		inc/SoundTest.h \
		inc/ui.h \
		inc/UploadMes.h \
		inc/WifiTest.h \
		inc/UiHandle.h \
		inc/messageform.h \
		inc/Control.h \
		inc/VideoTestThread.h \
		inc/ImageTestThread.h main.cpp \
		core/func/BrightTest.cpp \
		core/func/CamaraTest.cpp \
		core/func/EdidTest.cpp \
		core/func/FanTest.cpp \
		core/func/FuncBase.cpp \
		core/func/FuncTest.cpp \
		core/func/HddTest.cpp \
		core/func/MemTest.cpp \
		core/func/NetTest.cpp \
		core/func/NextProcess.cpp \
		core/func/SoundTest.cpp \
		core/func/StressTest.cpp \
		core/func/UploadMes.cpp \
		core/func/UsbTest.cpp \
		core/func/WifiTest.cpp \
		core/ui/UiHandle.cpp \
		utils/fac_log.cpp \
		utils/fac_utils.cpp \
		core/ui/DisplayTestWindow.cpp \
		core/ui/MainTestWindow.cpp \
		core/ui/StressTestWindow.cpp \
		core/ui/messageform.cpp \
		core/control/Control.cpp \
		core/ui/VideoTestThread.cpp \
		core/ui/ImageTestThread.cpp
QMAKE_TARGET  = Factory_test
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Factory_test


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Factory_test.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Factory_test.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile Factory_test.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
Factory_test.pro:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Factory_test.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents inc/Control.h inc/EdidTest.h inc/fac_log.h inc/fac_utils.h inc/FuncBase.h inc/FuncTest.h inc/NetTest.h inc/SoundTest.h inc/ui.h inc/UploadMes.h inc/WifiTest.h inc/UiHandle.h inc/messageform.h inc/Control.h inc/VideoTestThread.h inc/ImageTestThread.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp core/func/BrightTest.cpp core/func/CamaraTest.cpp core/func/EdidTest.cpp core/func/FanTest.cpp core/func/FuncBase.cpp core/func/FuncTest.cpp core/func/HddTest.cpp core/func/MemTest.cpp core/func/NetTest.cpp core/func/NextProcess.cpp core/func/SoundTest.cpp core/func/StressTest.cpp core/func/UploadMes.cpp core/func/UsbTest.cpp core/func/WifiTest.cpp core/ui/UiHandle.cpp utils/fac_log.cpp utils/fac_utils.cpp core/ui/DisplayTestWindow.cpp core/ui/MainTestWindow.cpp core/ui/StressTestWindow.cpp core/ui/messageform.cpp core/control/Control.cpp core/ui/VideoTestThread.cpp core/ui/ImageTestThread.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_Control.cpp moc_ui.cpp moc_UiHandle.cpp moc_messageform.cpp moc_Control.cpp moc_VideoTestThread.cpp moc_ImageTestThread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Control.cpp moc_ui.cpp moc_UiHandle.cpp moc_messageform.cpp moc_Control.cpp moc_VideoTestThread.cpp moc_ImageTestThread.cpp
moc_Control.cpp: inc/fac_utils.h \
		inc/MemTest.h \
		inc/Control.h \
		inc/FuncTest.h \
		inc/FuncBase.h \
		inc/SoundTest.h \
		inc/NetTest.h \
		inc/UiHandle.h \
		inc/ui.h \
		inc/VideoTestThread.h \
		inc/ImageTestThread.h \
		inc/messageform.h \
		inc/Control.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/root/work/Factory_test -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include inc/Control.h -o moc_Control.cpp

moc_ui.cpp: inc/VideoTestThread.h \
		inc/ui.h \
		inc/ImageTestThread.h \
		inc/messageform.h \
		inc/UiHandle.h \
		inc/ui.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/root/work/Factory_test -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include inc/ui.h -o moc_ui.cpp

moc_UiHandle.cpp: inc/ui.h \
		inc/VideoTestThread.h \
		inc/ImageTestThread.h \
		inc/messageform.h \
		inc/UiHandle.h \
		inc/UiHandle.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/root/work/Factory_test -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include inc/UiHandle.h -o moc_UiHandle.cpp

moc_messageform.cpp: inc/ui.h \
		inc/VideoTestThread.h \
		inc/ImageTestThread.h \
		inc/messageform.h \
		inc/UiHandle.h \
		inc/messageform.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/root/work/Factory_test -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include inc/messageform.h -o moc_messageform.cpp

moc_Control.cpp: inc/fac_utils.h \
		inc/MemTest.h \
		inc/Control.h \
		inc/FuncTest.h \
		inc/FuncBase.h \
		inc/SoundTest.h \
		inc/NetTest.h \
		inc/UiHandle.h \
		inc/ui.h \
		inc/VideoTestThread.h \
		inc/ImageTestThread.h \
		inc/messageform.h \
		inc/Control.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/root/work/Factory_test -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include inc/Control.h -o moc_Control.cpp

moc_VideoTestThread.cpp: inc/ui.h \
		inc/VideoTestThread.h \
		inc/ImageTestThread.h \
		inc/messageform.h \
		inc/UiHandle.h \
		inc/VideoTestThread.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/root/work/Factory_test -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include inc/VideoTestThread.h -o moc_VideoTestThread.cpp

moc_ImageTestThread.cpp: inc/ui.h \
		inc/VideoTestThread.h \
		inc/ImageTestThread.h \
		inc/messageform.h \
		inc/UiHandle.h \
		inc/ImageTestThread.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/root/work/Factory_test -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include inc/ImageTestThread.h -o moc_ImageTestThread.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp inc/Control.h \
		inc/fac_utils.h \
		inc/MemTest.h \
		inc/FuncBase.h \
		inc/FuncTest.h \
		inc/SoundTest.h \
		inc/NetTest.h \
		inc/UiHandle.h \
		inc/ui.h \
		inc/VideoTestThread.h \
		inc/ImageTestThread.h \
		inc/messageform.h \
		inc/fac_log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

BrightTest.o: core/func/BrightTest.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BrightTest.o core/func/BrightTest.cpp

CamaraTest.o: core/func/CamaraTest.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CamaraTest.o core/func/CamaraTest.cpp

EdidTest.o: core/func/EdidTest.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EdidTest.o core/func/EdidTest.cpp

FanTest.o: core/func/FanTest.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FanTest.o core/func/FanTest.cpp

FuncBase.o: core/func/FuncBase.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FuncBase.o core/func/FuncBase.cpp

FuncTest.o: core/func/FuncTest.cpp inc/FuncTest.h \
		inc/fac_utils.h \
		inc/Control.h \
		inc/MemTest.h \
		inc/FuncBase.h \
		inc/SoundTest.h \
		inc/NetTest.h \
		inc/UiHandle.h \
		inc/ui.h \
		inc/VideoTestThread.h \
		inc/ImageTestThread.h \
		inc/messageform.h \
		inc/fac_log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FuncTest.o core/func/FuncTest.cpp

HddTest.o: core/func/HddTest.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HddTest.o core/func/HddTest.cpp

MemTest.o: core/func/MemTest.cpp inc/MemTest.h \
		inc/Control.h \
		inc/fac_utils.h \
		inc/FuncTest.h \
		inc/FuncBase.h \
		inc/SoundTest.h \
		inc/NetTest.h \
		inc/UiHandle.h \
		inc/ui.h \
		inc/VideoTestThread.h \
		inc/ImageTestThread.h \
		inc/messageform.h \
		inc/fac_log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MemTest.o core/func/MemTest.cpp

NetTest.o: core/func/NetTest.cpp inc/NetTest.h \
		inc/Control.h \
		inc/fac_utils.h \
		inc/MemTest.h \
		inc/FuncBase.h \
		inc/FuncTest.h \
		inc/SoundTest.h \
		inc/UiHandle.h \
		inc/ui.h \
		inc/VideoTestThread.h \
		inc/ImageTestThread.h \
		inc/messageform.h \
		inc/fac_log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NetTest.o core/func/NetTest.cpp

NextProcess.o: core/func/NextProcess.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NextProcess.o core/func/NextProcess.cpp

SoundTest.o: core/func/SoundTest.cpp inc/SoundTest.h \
		inc/Control.h \
		inc/fac_utils.h \
		inc/MemTest.h \
		inc/FuncBase.h \
		inc/FuncTest.h \
		inc/NetTest.h \
		inc/UiHandle.h \
		inc/ui.h \
		inc/VideoTestThread.h \
		inc/ImageTestThread.h \
		inc/messageform.h \
		inc/fac_log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SoundTest.o core/func/SoundTest.cpp

StressTest.o: core/func/StressTest.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StressTest.o core/func/StressTest.cpp

UploadMes.o: core/func/UploadMes.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UploadMes.o core/func/UploadMes.cpp

UsbTest.o: core/func/UsbTest.cpp inc/FuncTest.h \
		inc/fac_utils.h \
		inc/Control.h \
		inc/MemTest.h \
		inc/FuncBase.h \
		inc/SoundTest.h \
		inc/NetTest.h \
		inc/UiHandle.h \
		inc/ui.h \
		inc/VideoTestThread.h \
		inc/ImageTestThread.h \
		inc/messageform.h \
		inc/fac_log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UsbTest.o core/func/UsbTest.cpp

WifiTest.o: core/func/WifiTest.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WifiTest.o core/func/WifiTest.cpp

UiHandle.o: core/ui/UiHandle.cpp inc/UiHandle.h \
		inc/ui.h \
		inc/VideoTestThread.h \
		inc/ImageTestThread.h \
		inc/messageform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UiHandle.o core/ui/UiHandle.cpp

fac_log.o: utils/fac_log.cpp inc/fac_log.h \
		inc/fac_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fac_log.o utils/fac_log.cpp

fac_utils.o: utils/fac_utils.cpp inc/fac_utils.h \
		inc/fac_log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fac_utils.o utils/fac_utils.cpp

DisplayTestWindow.o: core/ui/DisplayTestWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DisplayTestWindow.o core/ui/DisplayTestWindow.cpp

MainTestWindow.o: core/ui/MainTestWindow.cpp inc/ui.h \
		inc/VideoTestThread.h \
		inc/ImageTestThread.h \
		inc/messageform.h \
		inc/UiHandle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainTestWindow.o core/ui/MainTestWindow.cpp

StressTestWindow.o: core/ui/StressTestWindow.cpp inc/ui.h \
		inc/VideoTestThread.h \
		inc/ImageTestThread.h \
		inc/messageform.h \
		inc/UiHandle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StressTestWindow.o core/ui/StressTestWindow.cpp

messageform.o: core/ui/messageform.cpp inc/messageform.h \
		inc/ui.h \
		inc/VideoTestThread.h \
		inc/ImageTestThread.h \
		inc/UiHandle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o messageform.o core/ui/messageform.cpp

Control.o: core/control/Control.cpp inc/Control.h \
		inc/fac_utils.h \
		inc/MemTest.h \
		inc/FuncBase.h \
		inc/FuncTest.h \
		inc/SoundTest.h \
		inc/NetTest.h \
		inc/UiHandle.h \
		inc/ui.h \
		inc/VideoTestThread.h \
		inc/ImageTestThread.h \
		inc/messageform.h \
		inc/fac_log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Control.o core/control/Control.cpp

VideoTestThread.o: core/ui/VideoTestThread.cpp inc/VideoTestThread.h \
		inc/ui.h \
		inc/ImageTestThread.h \
		inc/messageform.h \
		inc/UiHandle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VideoTestThread.o core/ui/VideoTestThread.cpp

ImageTestThread.o: core/ui/ImageTestThread.cpp inc/ImageTestThread.h \
		inc/ui.h \
		inc/VideoTestThread.h \
		inc/messageform.h \
		inc/UiHandle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ImageTestThread.o core/ui/ImageTestThread.cpp

moc_Control.o: moc_Control.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Control.o moc_Control.cpp

moc_ui.o: moc_ui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ui.o moc_ui.cpp

moc_UiHandle.o: moc_UiHandle.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_UiHandle.o moc_UiHandle.cpp

moc_messageform.o: moc_messageform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_messageform.o moc_messageform.cpp

moc_VideoTestThread.o: moc_VideoTestThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_VideoTestThread.o moc_VideoTestThread.cpp

moc_ImageTestThread.o: moc_ImageTestThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ImageTestThread.o moc_ImageTestThread.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

